spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: event-service_service_route
          uri: lb://event-service
          predicates:
            - Path=/**
        - id: comment-service_service_route
          uri: lb://comment-service
          predicates:
            - Path=/**
        - id: request-service_service_route
          uri: lb://request-service
          predicates:
            - Path=/**
        - id: user-service_service_route
          uri: lb://user-service
          predicates:
            - Path=/**

server:
  port: 8080